---
version: "3.7"

volumes:
  traefik_logs:

services:
  traefik:
    image: "traefik:v3.2"
    ports:
      - "80:80"
      - "443:443"
      - "222:222"
      - "8080:8080"
    environment:
      DO_AUTH_TOKEN: "{{  DO_AUTH_TOKEN  }}"
    volumes:
      - /home/josiah/apps/letsencrypt/acme.json:/letsencrypt/acme.json
      - traefik_logs:/var/log/access.log
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/josiah/apps/traefik/traefik.yml:/traefik.yml
    dns:
      - 1.1.1.1
      - 8.8.8.8

    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik-svc.loadbalancer.server.port=8080"

  whoami:
    image: "traefik/whoami"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.halo.jowj.net`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=halo-resolver"
        - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"

  freshrss:
    image: linuxserver/freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/josiah/apps/freshrss:/config
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"
        - "traefik.http.routers.freshrss-rt.rule=Host(`rss.halo.jowj.net`)"
        - "traefik.http.routers.freshrss-rt.entrypoints=websecure"
        - "traefik.http.routers.freshrss-rt.tls.certresolver=halo-resolver"

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/josiah/apps/overseerr/config/:/config
    restart: unless-stopped
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
        - "traefik.http.routers.overseerr-rt.rule=Host(`requests.halo.jowj.net`)"
        - "traefik.http.routers.overseerr-rt.entrypoints=websecure"
        - "traefik.http.routers.overseerr-rt.tls.certresolver=halo-resolver"

  gitea:
    image: gitea/gitea:1.22.4
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /home/josiah/apps/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.gitea-svc.loadbalancer.server.port=3000"
        - "traefik.http.routers.gitea-rt.rule=Host(`git.halo.jowj.net`)"
        - "traefik.http.routers.gitea-rt.entrypoints=websecure"
        - "traefik.http.routers.gitea-rt.tls.certresolver=halo-resolver"

        # handle ssh
        - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.gitea-ssh.entrypoints=git-ssh"
        - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22"
