log:
  level: DEBUG

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  git-ssh:
    address: ":222"

providers:
  swarm:
    exposedByDefault: false
    watch: true

certificatesResolvers:
  halo-resolver:
    acme:
      email: "admin@home.jowj.net"
      storage: "/letsencrypt/acme.json"
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: "https://acme.zerossl.com/v2/DV90"
      eab:
        kid: "{{ VAULT_EAB_KID }}"
        hmacEncoded: "{{ VAULT_EAB_HMACENCODED }}"

      dnsChallenge:
        provider: "digitalocean"
        resolvers:
          - 1.1.1.1
          - 8.8.8.8
        delayBeforeCheck: 60
