sys_packages: [ 'curl', 'vim', 'git', 'fail2ban', 'mosh', 'emacs', 'build-essential','dnsutils', 'syncthing' ]
create_user: josiah
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/home-net.pub') }}"
syncthing_personal_service: syncthing@josiah
