---

global_acmedns_ssh_client_pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJkuNfpGFXrTiIE4KU8jU57VltMiMXapDcDEd3vWQcEm acmedns@jowj.net

remote_user: josiah
gather_facts: True
source_os: nixos
become: yes
create_user: josiah

# all of this is stolen from mrled, because fuck this is way better than what i was doing.
# Wireguard docs
# TODO: lookup plugin to generate the pubkey from the privkey
# TODO: set all these as hostvars, use hostvars['HOSTNAME'].wireguard_privkey etc
#       (should be ok even for e.g. glitch, which doesn't get provisioned from Ansible)
# To generate the keys:
# - wg genkey | tee privatekey | wg pubkey > publickey
# - save the privkey in the vault and the pubkey here
# - Delete the privatekey and publickey files

# GITEA shit.
GITEA_USER_UID: 1000
GITEA_USER_GID: 1000
GITEA_DB_TYPE: postgres
GITEA_DB_HOST: db:5432
GITEA_DB_NAME: "{{ lookup('community.general.onepassword', 'gitea-db', field='name', vault='Ansible') }}"
GITEA_DB_USER: "{{ lookup('community.general.onepassword', 'gitea-db', field='user', vault='Ansible') }}"
GITEA_DB_PASSWD: "{{ lookup('community.general.onepassword', 'gitea-db', field='password', vault='Ansible') }}"

GITEA_POSTGRES_USER: "{{ lookup('community.general.onepassword', 'gitea-postgres', field='user', vault='Ansible') }}"
GITEA_POSTGRES_PASSWORD: "{{ lookup('community.general.onepassword', 'gitea-postgres', field='password', vault='Ansible') }}"
GITEA_POSTGRES_DB: "{{ lookup('community.general.onepassword', 'gitea-postgres', field='db', vault='Ansible') }}"

# DO shit
DO_AUTH_TOKEN: "{{ lookup('community.general.onepassword', 'do-auth-token', vault='Ansible') }}"

