---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: ssh_server
  user:
    from_secret: ssh_user
  password:
    from_secret: ssh_pass

steps:
- name: greeting
  environment:
    USERNAME:
      from_secret: gitea_user
    PASSWORD:
      from_secret: gitea_pass
    IMAGE:
      from_secret: secret-image
  commands:
  - docker pull $IMAGE
  - echo $PASSWORD | docker login git.awful.club --username $USERNAME --password-stdin
  - docker image tag $IMAGE git.awful.club/packages/hoard
  - docker image push git.awful.club/packages/hoard
