kind: pipeline
type: docker
name: Update image

steps:
  
- name: Pull secret image and upload an updated copy to my package repo.
  image: alpine
  environment:
    USERNAME:
      from_secret: gitea-user
    PASSWORD:
      from_secret: gitea-key
    IMAGE:
      from_secret: secret-image
  commands:
    - apk add docker
    - docker login git.awful.club
    - docker pull $IMAGE
    - docker image tag {{ secret image name }} {{git.awful.club/packages/my_new_package}}
    - docker image push


image_pull_secrets:
- containerregistry-login
  
