---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: ssh_server
  user:
    from_secret: ssh_user
  password:
    from_secret: ssh_pass

steps:
- name: greeting
  commands:
  - echo hello world
  - hostname
  - whoami
