kind: pipeline
type: docker
name: Update image

steps:
  
- name: Pull secret image and upload an updated copy to my package repo.
  image: alpine
  auth_config: 
    username:
      from_secret: gitea-user
    password:
      from_secret: gitea-key
  environment:
    image:
      from_secret: secret-image
    
  commands:
    - apk add docker
    - docker login git.awful.club
    - docker pull $IMAGE
    - docker image tag $image git.awful.club/packages/hoard
    - docker image push


image_pull_secrets:
- containerregistry-login
  
