---
# deploy a halo host

# init new swarm, set up
- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    # advertise_addr: "100.108.51.49"

# If a DNS manager isn't available for your system, or you don't want to run one,
# and don't want Tailscale to overwrite /etc/resolv.conf,
# you can either disable MagicDNS for all devices in your tailnet or run
# tailscale set --accept-dns=false to disable MagicDNS on a single device.

- name: ensure the app folders exist
  file: state=directory path={{ item }} owner=alice group=alice mode=0700
  loop:
    [
      "/home/josiah/apps/letsencrypt/",
      "/home/josiah/apps/overseerr/config/",
      "/home/josiah/apps/freshrss",
      "/home/josiah/apps/traefik/",
      "/home/josiah/apps/gitea/",
      "/home/josiah/apps/drone/",
    ]

- name: copy over all halo config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { src: "halo-compose.yml", dest: "/home/josiah/apps/halo-compose.yml" }
    - { src: "traefik.yml", dest: "/home/josiah/apps/traefik/traefik.yml" }

# you have to force remove the whole stack for some changes to take effect
# I have no idea which ones, but this solved a problem for me with traefik conifgs + multi networks.
- name: Remove the halo stack
  block:
    - name: Remove the halo stack
      docker_stack:
        state: absent
        name: halo
        compose:
          - /home/josiah/apps/halo/halo-compose.yml

    - name: Delete a network
      docker_network:
        name: halo_pubnet
        state: absent
        force: yes
      ignore_errors: true

# - name: Create a network
#   docker_network:
#     name: pubnet
#     scope: swarm
#     attachable: true
#     driver: overlay

- name: Deploy halo stack
  docker_stack:
    state: present
    name: halo
    compose:
      - /home/josiah/apps/halo-compose.yml
