version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME={{ GITEA_DB_NAME }}
      - DB_USER={{ GITEA_DB_USER }}
      - DB_PASSWD={{ GITEA_DB_PASSWD }}
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/volume_sfo2_01/gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER={{ GITEA_POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ GITEA_POSTGRES_USER }}
      - POSTGRES_DB={{ GITEA_POSTGRES_USER }}
    networks:
      - gitea
    volumes:
      - /mnt/volume_sfo2_01/psql:/var/lib/postgresql/data
