version: "3.2"

# What is this?
#
# This stack exists solely to deploy the traefik_public overlay network, so that
# other stacks (including traefik-app) can attach to it

services:
  scratch:
    image: scratch
    deploy:
      replicas: 0
    networks:
      - pubnet

networks:
  pubnet:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.200.0/24
  privnet:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.219.0/24
          
