version: '3'

volumes:
  nextcloud:
  db:

services:
  nextcloud-db:
    image: postgres:9.6
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /mnt/shared_document_store/nextcloud/sql:/var/lib/postgresql
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - POSTGRES_ROOT_PASSWORD={{ NEXTCLOUD_POSTGRES_ROOT_PASSWORD }}
      - POSTGRES_PASSWORD={{ NEXTCLOUD_POSTGRES_PASSWORD }}
      - POSTGRES_DB={{ NEXTCLOUD_POSTGRES_DATABASE }}
      - POSTGRES_USER={{ NEXTCLOUD_POSTGRES_USER }}
      - POSTGRES_HOST={{ NEXTCLOUD_POSTGRES_HOST }}
      - NEXTCLOUD_ADMIN_USER={{ NEXTCLOUD_ADMIN_USER }}
      - NEXTCLOUD_ADMIN_PASSWORD={{ NEXTCLOUD_ADMIN_PASSWORD }}

  nextcloud-app:
    image: nextcloud:18
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /mnt/shared_document_store/nextcloud/html/:/var/www/html/
    depends_on:
      - db
    environment:
      - USER_UID=1000
      - USER_GID=1000      
      - POSTGRES_ROOT_PASSWORD={{ NEXTCLOUD_POSTGRES_ROOT_PASSWORD }}
      - POSTGRES_PASSWORD={{ NEXTCLOUD_POSTGRES_PASSWORD }}
      - POSTGRES_DB={{ NEXTCLOUD_POSTGRES_DATABASE }}
      - POSTGRES_USER={{ NEXTCLOUD_POSTGRES_USER }}
      - POSTGRES_HOST={{ NEXTCLOUD_POSTGRES_HOST }}
      - NEXTCLOUD_ADMIN_USER={{ NEXTCLOUD_ADMIN_USER }}
      - NEXTCLOUD_ADMIN_PASSWORD={{ NEXTCLOUD_ADMIN_PASSWORD }}
