all:
  children:
    util:
      hosts:
        util01:
          ansible_host: 64.225.41.192
          ansible_python_interpreter: /usr/bin/python3

    home:
      hosts:
        larva.home.jowj.net:
        lair:
          ansible_host: 192.168.1.120
    appliances:
      hosts:
        storage.home.jowj.net:
        cloudkey.home.jowj.net:
    dev:
      hosts:
        localhost:
          ansible_connection: local
    highsea:
      hosts:
        highsea.home.jowj.net:
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: alice
    testchat:
      hosts:
        mattermost-trial:
          ansible_host: 104.248.79.77
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: root
    services:
      hosts:
        lair:
          ansible_python_interpreter: /usr/bin/python3
    syslog:
      hosts:
        larva.home.jowj.net:
          ansible_python_interpreter: /usr/bin/python3
    halo:
      hosts:
        archon:
          ansible_host: 100.68.19.38
          ansible_python_interpreter: python3
          ansible_user: alice
    bikeshed:
      hosts:
        seraph:
          ansible_python_interpreter: /usr/bin/python3
        demiurge:
          ansible_python_interpreter: /usr/bin/python3
        exgod:
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_user: root
