all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
          ansible_python_interpreter: python3
    home:
      hosts:
        hatchery.home.jowj.net:
        larva.home.jowj.net:
        lair:
          ansible_host: 192.168.1.120
    appliances:
      hosts:
        storage.home.jowj.net:
        cloudkey.home.jowj.net:
    dev:
      hosts:
        localhost:
          ansible_connection: local
    highsea:
      hosts:
        highsea.home.jowj.net:
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: alice
    services:
      hosts:
        lair:
          ansible_python_interpreter: /usr/bin/python3
    syslog:
      hosts:
        larva.home.jowj.net:
          ansible_python_interpreter: /usr/bin/python3
    halo:
      hosts:
        halo.awful.club:
          ansible_python_interpreter: python3
    bikeshed:
      hosts:
        seraph:
          ansible_python_interpreter: /usr/bin/python3
        demiurge:
          ansible_python_interpreter: /usr/bin/python3
        exgod:
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_user: root        
