all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
          ansible_python_interpreter: /usr/local/bin/python3.7
    home:
      hosts:
        hatchery.home.jowj.net:
        larva.home.jowj.net:
        storage.home.jowj.net:
    vpn:
      hosts:
        vpn.awful.club:
    dev:
      hosts:
        localhost:
          ansible_connection: local
    onprem_clients:
      hosts:
        hydra-ling:
        lurker-ling:
        ling-bane:
        little-lady:
    mediaserver:
      hosts:
        hatchery:
          ansible_python_interpreter: /usr/bin/python3
    syslog:
      hosts:
        larva.home.jowj.net:
          ansible_python_interpreter: /usr/bin/python3
