---

# Update the mojo git repo
- name: ensure the app folders exist
  file: state=directory path={{ item }} owner=josiah group=josiah mode=0700
  loop: [ '/home/josiah/apps/mojo/', '/home/josiah/apps/arke/', '/home/josiah/apps/znc/', '/home/josiah/apps/awful/' ]
  
- name: update the mojo git repo
  git:
    repo: 'https://git.awful.club/hosted/mojojojo-bot.git'
    dest: /home/josiah/apps/mojo/
    version: master

- name: update the arke git repo
  git:
    repo: 'https://git.awful.club/hosted/arke.git'
    dest: /home/josiah/apps/arke/
    version: master

- name: update the znc git repo
  git:
    repo: 'https://git.awful.club/hosted/znc-docker.git'
    dest: /home/josiah/apps/znc/
    version: master

- name: copy over awful-All compose file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - {src: 'awful-compose.yml', dest: '/home/josiah/apps/awful/docker-compose.yml'}

- name: Deploy awful stack
  docker_compose:
    state: present
    project_src: "/home/josiah/apps/awful/"
