version: '3'

networks:
  gitea:
    external: false

volumes:
  nextcloud:
  db:
  traefik_acme:
  traefik_logs:
  nginx_logs:
    
services:      

  traefik:
    image: "traefik:v2.2"
    ports:
      - "80:80"
      - "443:443"
      - "222:222"
      - "8080:8080"
    environment:
      DO_AUTH_TOKEN: "{{ DO_AUTH_TOKEN }}"
    volumes:
      - "/home/josiah/apps/awful/letsencrypt/:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/josiah/apps/test/traefik.yml:/etc/traefik/traefik.yml"
      - traefik_logs:/log

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.awful.club`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=awful-letsencrypt"

  nginx: 
    image: nginx:1.17.10
    volumes:
      - /etc/nginx/:/etc/nginx/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /home/josiah/apps/awful/awful.club.html:/var/www/awful.club/html/index.html
      - nginx_logs:/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`awful.club`)||Host(`jowj.net`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=awful-letsencrypt"
