---

- name: Ensure the apps/nextcloud directory exists
  file: state=directory path=/home/josiah/apps/nextcloud/ owner=josiah group=josiah mode=0700

- name: copy over nextcloud config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - {src: 'nextcloud-compose.yml', dest: '/home/josiah/apps/nextcloud/docker-compose.yml'}

- name: Deploy the nextcloud stack.
  docker_compose:
    state: present
    project_src: "/home/josiah/apps/nextcloud/"
    
