---

- name: Download Tailscale signing key (ubuntu)
  get_url:
    url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add Tailscale repository (ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    filename: tailscale
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Download Tailscale signing key (debian)
  get_url:
    url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'
  become: true
  when: ansible_distribution == "Debian"

- name: Add Tailscale repository (debian)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main"
    filename: tailscale
    state: present
  become: true
  when: ansible_distribution == "Debian"

- name: Install packages
  apt:
    name:
      - tailscale
    state: present
  become: true

- name: Connect machine to your Tailscale network
  command: tailscale up --authkey {{ tailscale_auth_key }} {{ tailscale_extra_args }}
  changed_when: no
  become: true
