- name: deploy highsea stack
  hosts: highsea
  remote_user: "{{ remote_user }}"
  tasks:
    - debug: msg="Deploying mediaserver stack to local server"
  roles:
#    - { name: debian_base }
    - { name: highsea }
