---
- name: cloud wg config
  hosts: vpn
  gather_facts: no  
  tasks:
    - debug: msg="Deploying wg to cloud server"
  roles:
    - { name: wg_vpn, tags: ['wg_vpn'] }

- name: deploy the awful stack
  gather_facts: no  
  hosts: prod
  tasks:
    - debug: msg="Deploying awful stack to cloud server"
  roles:
    - { name: awfulAll, tags: ['awfulAll'] }


- name: Deploy mediaserver
  hosts: mediaserver
  gather_facts: no
  roles:
    - { name: mediaserver, tags: ['mediaserver'] }    


- name: Deploy gitea
  hosts: dockerhosts
  gather_facts: no
  roles:
    - { name: gitea, tags: ['gitea'] }

- name: Deploy nextcloud
  hosts: dockerhosts
  gather_facts: no
  roles:
    - { name: nextcloud, tags: ['nextcloud'] }
    
