---
- name: cloud wg config
  hosts: vpn
  tasks:
    - debug: msg="Deploying wg to cloud server"
  roles:
    - { name: wg_vpn, tags: ['wg_vpn'] }

- name: deploy the awful stack
  hosts: prod
  tasks:
    - debug: msg="Deploying awful stack to cloud server"
  roles:
    - { name: awfulAll, tags: ['awfulAll'] }


- name: Deploy mediaserver
  hosts: mediaserver
  roles:
    - { name: mediaserver, tags: ['mediaserver'] }    
