all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
          ansible_python_interpreter: /usr/local/bin/python3.7
    vpn:
      hosts:
        vpn.awful.club:
    dev:
      hosts:
        localhost:
          ansible_connection: local
    onprem_clients:
      hosts:
        hydra-ling:
        lurker-ling:
        ling-bane:
    mediaserver:
      hosts:
        hatchery:
          ansible_python_interpreter: /usr/bin/python3
