all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
    vpn:
      hosts:
        vpn.awful.club:
    dev:
      hosts:
        localhost:
    onprem_clients:
      hosts:
        hydra-ling:
        lurker-ling:
        ling-bane:
    onprem_servers:
      hosts:
        hatchery:
    mediaservers:
      hosts:
        hatchery:
